spring:
  application:
    name: blogs
  datasource:
    url: jdbc:postgresql://localhost:5432/blogs
    username: yhaddar
    password: 3705
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-discovery:8871/eureka/
      register-with-eureka: true
      fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: blogs_service