spring:
  application:
    name: recipe
  datasource:
    url: jdbc:postgresql://localhost:5433/recipes
    username: yhaddar
    password: 3705
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
